<?php
/**
 * Generated Hook Cache
 *
 * This file is automatically generated by the Manager class.
 * It contains a mapped array of classes and their respective WordPress hooks.
 *
 * @package    WP_Bootstrapper
 * @subpackage Cache
 * @author     Konstantin Sorokin
 * @link       https://konstantinsorokin.com
 */

defined( 'ABSPATH' ) || exit;

return array (
  'WPB\\Settings\\Config' => 
  array (
    0 => 
    array (
      'hook' => 'init',
      'method' => 'register',
      'priority' => 10,
      'args' => 1,
    ),
  ),
  'WPB\\Cookies' => 
  array (
    0 => 
    array (
      'hook' => 'init',
      'method' => 'set_referer_cookie',
      'priority' => 1,
      'args' => 1,
    ),
  ),
  'WPB\\Plugins\\TranslatePress' => 
  array (
    0 => 
    array (
      'hook' => 'wp_enqueue_scripts',
      'method' => 'dequeue_style',
      'priority' => 9000,
      'args' => 1,
    ),
    1 => 
    array (
      'hook' => 'trp_beautify_language_name',
      'method' => 'shorten_language_names',
      'priority' => 10,
      'args' => 3,
    ),
  ),
  'WPB\\Gutenberg' => 
  array (
    0 => 
    array (
      'hook' => 'wp_body_open',
      'method' => 'remove_svg_filters',
      'priority' => 10,
      'args' => 1,
    ),
    1 => 
    array (
      'hook' => 'in_admin_header',
      'method' => 'remove_admin_svg_filters',
      'priority' => 10,
      'args' => 1,
    ),
    2 => 
    array (
      'hook' => 'wp_enqueue_scripts',
      'method' => 'remove_global_styles',
      'priority' => 10,
      'args' => 1,
    ),
    3 => 
    array (
      'hook' => 'init',
      'method' => 'remove_duotone_support',
      'priority' => 10,
      'args' => 1,
    ),
    4 => 
    array (
      'hook' => 'init',
      'method' => 'remove_group_inner_container',
      'priority' => 10,
      'args' => 1,
    ),
    5 => 
    array (
      'hook' => 'init',
      'method' => 'remove_layout_support',
      'priority' => 10,
      'args' => 1,
    ),
    6 => 
    array (
      'hook' => 'should_load_separate_core_block_assets',
      'method' => 'disable_separate_assets',
      'priority' => 10,
      'args' => 1,
    ),
    7 => 
    array (
      'hook' => 'wp_enqueue_scripts',
      'method' => 'dequeue_block_styles',
      'priority' => 100,
      'args' => 1,
    ),
    8 => 
    array (
      'hook' => 'wp_footer',
      'method' => 'remove_footer_assets',
      'priority' => 10,
      'args' => 1,
    ),
    9 => 
    array (
      'hook' => 'wp_omit_duotone_inline_styles',
      'method' => 'omit_duotone_styles',
      'priority' => 10,
      'args' => 1,
    ),
    10 => 
    array (
      'hook' => 'init',
      'method' => 'disable_block_patterns',
      'priority' => 10,
      'args' => 1,
    ),
  ),
  'WPB\\Files' => 
  array (
    0 => 
    array (
      'hook' => 'big_image_size_threshold',
      'method' => 'big_image_size_threshold',
      'priority' => 10,
      'args' => 1,
    ),
    1 => 
    array (
      'hook' => 'sanitize_file_name',
      'method' => 'clear_file_name',
      'priority' => 10,
      'args' => 1,
    ),
    2 => 
    array (
      'hook' => 'upload_mimes',
      'method' => 'svg_svgz_support',
      'priority' => 10,
      'args' => 1,
    ),
    3 => 
    array (
      'hook' => 'wp_handle_upload_prefilter',
      'method' => 'validate_svg_upload',
      'priority' => 10,
      'args' => 1,
    ),
  ),
  'WPB\\Theme' => 
  array (
    0 => 
    array (
      'hook' => 'get_the_archive_title',
      'method' => 'clean_archive_title',
      'priority' => 10,
      'args' => 1,
    ),
  ),
  'WPB\\JavaScript' => 
  array (
    0 => 
    array (
      'hook' => 'wp_enqueue_scripts',
      'method' => 'jquery',
      'priority' => 100,
      'args' => 1,
    ),
    1 => 
    array (
      'hook' => 'wp_default_scripts',
      'method' => 'jquery_migrate',
      'priority' => 10,
      'args' => 1,
    ),
    2 => 
    array (
      'hook' => 'init',
      'method' => 'oembed_full',
      'priority' => 10,
      'args' => 1,
    ),
    3 => 
    array (
      'hook' => 'init',
      'method' => 'stopHeartbeat',
      'priority' => 1,
      'args' => 1,
    ),
    4 => 
    array (
      'hook' => 'wp_print_scripts',
      'method' => 'autosave_script',
      'priority' => 10,
      'args' => 1,
    ),
    5 => 
    array (
      'hook' => 'admin_print_scripts',
      'method' => 'autosave_script',
      'priority' => 10,
      'args' => 1,
    ),
    6 => 
    array (
      'hook' => 'script_loader_tag',
      'method' => 'set_async_defer_attribute',
      'priority' => 10,
      'args' => 3,
    ),
  ),
  'WPB\\Users' => 
  array (
    0 => 
    array (
      'hook' => 'user_contactmethods',
      'method' => 'updateContactMethods',
      'priority' => 10,
      'args' => 1,
    ),
  ),
  'WPB\\Cron' => 
  array (
    0 => 
    array (
      'hook' => 'cron_schedules',
      'method' => 'add_intervals',
      'priority' => 10,
      'args' => 1,
    ),
  ),
  'WPB\\Head' => 
  array (
    0 => 
    array (
      'hook' => 'init',
      'method' => 'clean_head',
      'priority' => 10,
      'args' => 1,
    ),
    1 => 
    array (
      'hook' => 'wp_head',
      'method' => 'phone_detection',
      'priority' => 5,
      'args' => 1,
    ),
    2 => 
    array (
      'hook' => 'wp_head',
      'method' => 'geo_region',
      'priority' => 5,
      'args' => 1,
    ),
    3 => 
    array (
      'hook' => 'send_headers',
      'method' => 'content_security_policy_header',
      'priority' => 10,
      'args' => 1,
    ),
    4 => 
    array (
      'hook' => 'wp_head',
      'method' => 'content_security_policy',
      'priority' => 1,
      'args' => 1,
    ),
    5 => 
    array (
      'hook' => 'send_headers',
      'method' => 'x_frame_header',
      'priority' => 10,
      'args' => 1,
    ),
    6 => 
    array (
      'hook' => 'run_wptexturize',
      'method' => 'run_wptexturize',
      'priority' => 10,
      'args' => 1,
    ),
    7 => 
    array (
      'hook' => 'wp_head',
      'method' => 'x_frame_options',
      'priority' => 5,
      'args' => 1,
    ),
  ),
  'WPB\\Backend' => 
  array (
    0 => 
    array (
      'hook' => 'admin_bar_menu',
      'method' => 'remove_wp_logo',
      'priority' => 999,
      'args' => 1,
    ),
    1 => 
    array (
      'hook' => 'update_footer',
      'method' => 'remove_footer_version',
      'priority' => 99,
      'args' => 1,
    ),
    2 => 
    array (
      'hook' => 'admin_footer_text',
      'method' => 'remove_footer_text',
      'priority' => 99,
      'args' => 1,
    ),
    3 => 
    array (
      'hook' => 'admin_init',
      'method' => 'remove_welcome_panel',
      'priority' => 10,
      'args' => 1,
    ),
    4 => 
    array (
      'hook' => 'admin_menu',
      'method' => 'register_action_scheduler_menu',
      'priority' => 9999,
      'args' => 1,
    ),
  ),
);