<?php
/**
 * Generated Hook Cache
 *
 * This file is automatically generated by the Manager class.
 * It contains a mapped array of classes and their respective WordPress hooks.
 *
 * @package    WP_Bootstrapper
 * @subpackage Cache
 * @author     Konstantin Sorokin
 * @link       https://konstantinsorokin.com
 */

defined( 'ABSPATH' ) || exit;

return array (
  'WPB\\Settings\\Config' => 
  array (
    0 => 
    array (
      'hook' => 'init',
      'method' => 'register',
      'priority' => 10,
      'args' => 1,
    ),
  ),
  'WPB\\Cookies' => 
  array (
    0 => 
    array (
      'hook' => 'init',
      'method' => 'setRefererCookie',
      'priority' => 1,
      'args' => 1,
    ),
  ),
  'WPB\\Files' => 
  array (
    0 => 
    array (
      'hook' => 'big_image_size_threshold',
      'method' => 'disableBigImageThreshold',
      'priority' => 10,
      'args' => 1,
    ),
    1 => 
    array (
      'hook' => 'sanitize_file_name',
      'method' => 'clearFileName',
      'priority' => 10,
      'args' => 1,
    ),
    2 => 
    array (
      'hook' => 'upload_mimes',
      'method' => 'svg_svgz_support',
      'priority' => 10,
      'args' => 1,
    ),
  ),
  'WPB\\JavaScript' => 
  array (
    0 => 
    array (
      'hook' => 'wp_default_scripts',
      'method' => 'disable_jquery_migrate',
      'priority' => 10,
      'args' => 1,
    ),
  ),
  'WPB\\Cron' => 
  array (
    0 => 
    array (
      'hook' => 'cron_schedules',
      'method' => 'addIntervals',
      'priority' => 10,
      'args' => 1,
    ),
  ),
  'WPB\\Head' => 
  array (
    0 => 
    array (
      'hook' => 'init',
      'method' => 'clean_head',
      'priority' => 10,
      'args' => 1,
    ),
  ),
  'WPB\\Backend' => 
  array (
    0 => 
    array (
      'hook' => 'admin_bar_menu',
      'method' => 'removeWpLogo',
      'priority' => 999,
      'args' => 1,
    ),
    1 => 
    array (
      'hook' => 'update_footer',
      'method' => 'remove_footer_version',
      'priority' => 99,
      'args' => 1,
    ),
    2 => 
    array (
      'hook' => 'admin_footer_text',
      'method' => 'remove_footer_text',
      'priority' => 99,
      'args' => 1,
    ),
    3 => 
    array (
      'hook' => 'admin_init',
      'method' => 'remove_welcome_panel',
      'priority' => 10,
      'args' => 1,
    ),
  ),
);