<?php
/**
 * Hook Manager and Bootstrapper
 *
 * Handles the discovery, caching, and lazy registration of WordPress hooks
 * using PHP Attributes and the Reflection API.
 *
 * @package    KS_Bootstrapper
 * @subpackage Core
 * @author     Konstantin Sorokin
 * @link       https://konstantinsorokin.com
 */

namespace KonstantinSorokin\Bootstrapper\Core;

use Generator;
use ReflectionClass;
use ReflectionMethod;
use KonstantinSorokin\Bootstrapper\Attributes\Hook;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;
use Throwable;

defined( 'ABSPATH' ) || exit;

final class Manager {

    /**
     * Storage for single instances of classes (Singleton pattern within the bootstrapper).
     *
     * @var array<string, object>
     */
    private array $instances = [];

    /**
     * Whether the "cache is not writable" admin notice has already been queued for this request.
     *
     * @var bool
     */
    private bool $noticeQueued = false;

    /**
     * Constructor.
     *
     * @param string $appDir          The absolute path to the application directory to scan.
     * @param string $namespacePrefix The base namespace prefix for the application classes.
     * @param string $cacheFile       The absolute path to the generated cache file.
     * @param string $version         Optional. The plugin version stamped into the cache. A mismatch rebuilds it. Default ''.
     */
    public function __construct(
        private readonly string $appDir,
        private readonly string $namespacePrefix,
        private readonly string $cacheFile,
        private readonly string $version = ''
    ) {}

    /**
     * Initializes the hook registration system.
     *
     * The cache is reused only when it was generated by this plugin version from these exact
     * sources; otherwise the hook map is rebuilt in memory and written back atomically. A cache
     * that cannot be read or written never stops the request — the in-memory map is used instead.
     *
     * @return void
     * @throws \ReflectionException
     */
    public function boot(): void {
        $config = $this->load_cache();

        if ( null === $config ) {
            $mtime  = $this->max_source_mtime();
            $config = $this->scan_hooks();

            $this->write_cache( $config, $mtime );
        }

        $this->register_hooks( $config );
    }

    /**
     * Reads the generated cache file and validates that it still describes the current sources.
     *
     * @return array|null The cached hook map, or null when the cache is missing, damaged or stale.
     */
    private function load_cache(): ?array {
        if ( ! is_readable( $this->cacheFile ) ) {
            return null;
        }

        try {
            $cached = include $this->cacheFile;
        } catch ( Throwable ) {
            // A damaged cache file must never take the site down.
            return null;
        }

        if ( ! is_array( $cached ) || ! isset( $cached['hooks'] ) || ! is_array( $cached['hooks'] ) ) {
            return null;
        }

        if ( ( $cached['version'] ?? null ) !== $this->version ) {
            return null;
        }

        if ( ( $cached['mtime'] ?? null ) !== $this->max_source_mtime() ) {
            return null;
        }

        return $cached['hooks'];
    }

    /**
     * Scans the application directory and builds the hook map in memory.
     *
     * @return array Map of class names to their hook configurations.
     * @throws \ReflectionException
     */
    private function scan_hooks(): array {
        $hooksConfig = [];

        foreach ( $this->php_files() as $file ) {
            $className = $this->resolve_class_name( $file->getPathname() );

            if ( $className && class_exists( $className ) ) {
                $classHooks = $this->reflect_class_hooks( $className );

                if ( ! empty( $classHooks ) ) {
                    $hooksConfig[ $className ] = $classHooks;
                }
            }
        }

        return $hooksConfig;
    }

    /**
     * Writes the hook map to disk as a static PHP file, stamped with the version and source mtime.
     *
     * The file is written to a temporary neighbour and renamed into place, so a concurrent request
     * always reads either the previous or the new file, never a half-written one.
     *
     * @param array $hooksConfig The hook map to store.
     * @param int   $mtime       The newest source modification time the map was built from.
     *
     * @return void
     */
    private function write_cache( array $hooksConfig, int $mtime ): void {
        $directory = dirname( $this->cacheFile );

        if ( ! is_dir( $directory ) && ! wp_mkdir_p( $directory ) ) {
            $this->queue_cache_notice();

            return;
        }

        $payload = [
            'version' => $this->version,
            'mtime'   => $mtime,
            'hooks'   => $hooksConfig,
        ];

        $export  = var_export( $payload, true ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_var_export
        $content = "<?php" . PHP_EOL;
        $content .= "/**" . PHP_EOL;
        $content .= " * Generated Hook Cache" . PHP_EOL;
        $content .= " *" . PHP_EOL;
        $content .= " * This file is automatically generated by the Manager class." . PHP_EOL;
        $content .= " * It contains a mapped array of classes and their respective WordPress hooks." . PHP_EOL;
        $content .= " *" . PHP_EOL;
        $content .= " * @package    KS_Bootstrapper" . PHP_EOL;
        $content .= " * @subpackage Cache" . PHP_EOL;
        $content .= " * @author     Konstantin Sorokin" . PHP_EOL;
        $content .= " * @link       https://konstantinsorokin.com" . PHP_EOL;
        $content .= " */" . PHP_EOL . PHP_EOL;
        $content .= "defined( 'ABSPATH' ) || exit;" . PHP_EOL . PHP_EOL;
        $content .= "return {$export};";

        $temporary = tempnam( $directory, 'ks_hooks_' );

        // An unwritable target makes tempnam() fall back to the system directory,
        // where the rename below would no longer be atomic.
        if ( false === $temporary || realpath( dirname( $temporary ) ) !== realpath( $directory ) ) {
            if ( is_string( $temporary ) ) {
                wp_delete_file( $temporary );
            }

            $this->queue_cache_notice();

            return;
        }

        if ( false === file_put_contents( $temporary, $content ) ) {
            wp_delete_file( $temporary );
            $this->queue_cache_notice();

            return;
        }

        chmod( $temporary, 0644 );

        if ( ! rename( $temporary, $this->cacheFile ) ) {
            wp_delete_file( $temporary );
            $this->queue_cache_notice();

            return;
        }

        if ( function_exists( 'opcache_invalidate' ) ) {
            opcache_invalidate( $this->cacheFile, true );
        }
    }

    /**
     * Queues a one-time admin notice explaining that the hook cache cannot be written.
     *
     * @return void
     */
    private function queue_cache_notice(): void {
        if ( $this->noticeQueued || ! is_admin() ) {
            return;
        }

        $this->noticeQueued = true;

        add_action( 'admin_notices', static function (): void {
            if ( ! current_user_can( 'manage_options' ) ) {
                return;
            }

            printf(
                '<div class="notice notice-error"><p>%s</p></div>',
                esc_html__( 'KS Bootstrapper: the hook cache could not be written. The plugin still works, but its hook map is rebuilt on every request. Make the plugin\'s "cache" directory writable to restore normal performance.', 'ks-bootstrapper' )
            );
        } );
    }

    /**
     * Returns the modification time of the most recently changed source file.
     *
     * @return int Unix timestamp, or 0 when the application directory holds no sources.
     */
    private function max_source_mtime(): int {
        $newest = 0;

        foreach ( $this->php_files() as $file ) {
            $newest = max( $newest, (int) $file->getMTime() );
        }

        return $newest;
    }

    /**
     * Iterates over every PHP source file inside the application directory.
     *
     * @return Generator<SplFileInfo>
     */
    private function php_files(): Generator {
        if ( ! is_dir( $this->appDir ) ) {
            return;
        }

        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator( $this->appDir, RecursiveDirectoryIterator::SKIP_DOTS )
        );

        /** @var SplFileInfo $file */
        foreach ( $iterator as $file ) {
            if ( $file->isFile() && $file->getExtension() === 'php' ) {
                yield $file;
            }
        }
    }

    /**
     * Analyzes a class using the Reflection API to extract hook metadata.
     *
     * @param string $className The Fully Qualified Class Name to reflect.
     *
     * @return array Array of hook configurations found in the class.
     * @throws \ReflectionException
     */
    private function reflect_class_hooks( string $className ): array {
        $hooks      = [];
        $reflection = new ReflectionClass( $className );

        foreach ( $reflection->getMethods( ReflectionMethod::IS_PUBLIC ) as $method ) {
            $attributes = $method->getAttributes( Hook::class );

            foreach ( $attributes as $attribute ) {
                /** @var Hook $hook */
                $hook = $attribute->newInstance();

                $hooks[] = [
                    'hook'     => $hook->name,
                    'method'   => $method->getName(),
                    'priority' => $hook->priority,
                    'args'     => $hook->accepted_args,
                ];
            }
        }

        return $hooks;
    }

    /**
     * Registers hooks from the given map without utilizing Reflection.
     * Uses lazy initialization to ensure objects are only instantiated when their hook fires.
     *
     * @param array $config Map of class names to their hook configurations.
     *
     * @return void
     */
    private function register_hooks( array $config ): void {
        foreach ( $config as $className => $hooks ) {
            if ( ! is_array( $hooks ) ) {
                continue;
            }

            // Lazy initialization: the object is created only upon the hook execution
            $getInstance = function () use ( $className ): ?object {
                if ( ! class_exists( $className ) ) {
                    return null;
                }

                return $this->instances[ $className ] ??= new $className();
            };

            foreach ( $hooks as $hookInfo ) {
                if ( ! isset( $hookInfo['hook'], $hookInfo['method'] ) ) {
                    continue;
                }

                // Closure wrapper for method execution
                $callback = function ( ...$args ) use ( $getInstance, $hookInfo ) {
                    $instance = $getInstance();

                    // A class or method dropped by an update must not fatal when its hook fires.
                    if ( null === $instance || ! method_exists( $instance, $hookInfo['method'] ) ) {
                        return $args[0] ?? null;
                    }

                    return $instance->{$hookInfo['method']}( ...$args );
                };

                // In WordPress, add_filter works for both filters and actions
                add_filter(
                    $hookInfo['hook'],
                    $callback,
                    (int) ( $hookInfo['priority'] ?? 10 ),
                    (int) ( $hookInfo['args'] ?? 1 )
                );
            }
        }
    }

    /**
     * Converts a physical file path into a Fully Qualified Class Name (FQCN) based on the PSR-4 standard.
     *
     * @param string $path The absolute file path.
     *
     * @return string|null The resolved class name, or null if it cannot be resolved.
     */
    private function resolve_class_name( string $path ): ?string {
        $relativePath = str_replace( $this->appDir, '', $path );
        $relativePath = ltrim( $relativePath, DIRECTORY_SEPARATOR );
        $classPath    = str_replace( [ '/', '.php' ], [ '\\', '' ], $relativePath );

        return rtrim( $this->namespacePrefix, '\\' ) . '\\' . $classPath;
    }

}
