<?php
/**
 * Hook Manager and Bootstrapper
 *
 * Handles the discovery, caching, and lazy registration of WordPress hooks
 * using PHP Attributes and the Reflection API.
 *
 * @package    WP_Bootstrapper
 * @subpackage Core
 * @author     Konstantin Sorokin
 * @link       https://konstantinsorokin.com
 */

namespace WPB\Core;

use ReflectionClass;
use ReflectionMethod;
use WPB\Attributes\Hook;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;

defined( 'ABSPATH' ) || exit;

final class Manager {

    /**
     * Storage for single instances of classes (Singleton pattern within the bootstrapper).
     *
     * @var array<string, object>
     */
    private array $instances = [];

    /**
     * Constructor.
     *
     * @param string $appDir          The absolute path to the application directory to scan.
     * @param string $namespacePrefix The base namespace prefix for the application classes.
     * @param string $cacheFile       The absolute path to the generated cache file.
     * @param bool   $isDebug         Optional. Whether debug mode is enabled. If true, the cache is rebuilt on every request. Default false.
     */
    public function __construct(
        private readonly string $appDir,
        private readonly string $namespacePrefix,
        private readonly string $cacheFile,
        private readonly bool $isDebug = false
    ) {}

    /**
     * Initializes the hook registration system.
     * * Rebuilds the cache if it doesn't exist or if debug mode is active,
     * and then proceeds to register all discovered hooks.
     *
     * @return void
     * @throws \ReflectionException
     */
    public function boot(): void {
        // Rebuild cache if it's missing or if debugging is enabled
        if ( $this->isDebug || ! file_exists( $this->cacheFile ) ) {
            $this->buildCache();
        }

        $this->registerHooks();
    }

    /**
     * Scans the directory and generates a static PHP cache file containing hook configurations.
     *
     * @return void
     * @throws \ReflectionException
     */
    private function buildCache(): void {
        $hooksConfig = [];

        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator( $this->appDir )
        );

        /** @var SplFileInfo $file */
        foreach ( $iterator as $file ) {
            if ( $file->isFile() && $file->getExtension() === 'php' ) {
                $className = $this->resolveClassName( $file->getPathname() );

                if ( $className && class_exists( $className ) ) {
                    $classHooks = $this->reflectClassHooks( $className );
                    if ( ! empty( $classHooks ) ) {
                        $hooksConfig[ $className ] = $classHooks;
                    }
                }
            }
        }

        // Prepare the file content with security check and exported array
        $export  = var_export( $hooksConfig, true ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_var_export
        $content = "<?php" . PHP_EOL;
        $content .= "/**" . PHP_EOL;
        $content .= " * Generated Hook Cache" . PHP_EOL;
        $content .= " *" . PHP_EOL;
        $content .= " * This file is automatically generated by the Manager class." . PHP_EOL;
        $content .= " * It contains a mapped array of classes and their respective WordPress hooks." . PHP_EOL;
        $content .= " *" . PHP_EOL;
        $content .= " * @package    WP_Bootstrapper" . PHP_EOL;
        $content .= " * @subpackage Cache" . PHP_EOL;
        $content .= " * @author     Konstantin Sorokin" . PHP_EOL;
        $content .= " * @link       https://konstantinsorokin.com" . PHP_EOL;
        $content .= " */" . PHP_EOL . PHP_EOL;
        $content .= "defined( 'ABSPATH' ) || exit;" . PHP_EOL . PHP_EOL;
        $content .= "return {$export};";

        file_put_contents( $this->cacheFile, $content );
    }

    /**
     * Analyzes a class using the Reflection API to extract hook metadata.
     *
     * @param string $className The Fully Qualified Class Name to reflect.
     *
     * @return array Array of hook configurations found in the class.
     * @throws \ReflectionException
     */
    private function reflectClassHooks( string $className ): array {
        $hooks      = [];
        $reflection = new ReflectionClass( $className );

        foreach ( $reflection->getMethods( ReflectionMethod::IS_PUBLIC ) as $method ) {
            $attributes = $method->getAttributes( Hook::class );

            foreach ( $attributes as $attribute ) {
                /** @var Hook $hook */
                $hook = $attribute->newInstance();

                $hooks[] = [
                    'hook'     => $hook->name,
                    'method'   => $method->getName(),
                    'priority' => $hook->priority,
                    'args'     => $hook->accepted_args,
                ];
            }
        }

        return $hooks;
    }

    /**
     * Registers hooks directly from the cache file without utilizing Reflection.
     * * Uses lazy initialization to ensure objects are only instantiated when their hook fires.
     *
     * @return void
     */
    private function registerHooks(): void {
        $config = require $this->cacheFile;

        foreach ( $config as $className => $hooks ) {
            // Lazy initialization: the object is created only upon the hook execution
            $getInstance = function () use ( $className ): object {
                return $this->instances[ $className ] ??= new $className();
            };

            foreach ( $hooks as $hookInfo ) {
                // Closure wrapper for method execution
                $callback = function ( ...$args ) use ( $getInstance, $hookInfo ) {
                    return $getInstance()->{$hookInfo['method']}( ...$args );
                };

                // In WordPress, add_filter works for both filters and actions
                add_filter(
                    $hookInfo['hook'],
                    $callback,
                    $hookInfo['priority'],
                    $hookInfo['args']
                );
            }
        }
    }

    /**
     * Converts a physical file path into a Fully Qualified Class Name (FQCN) based on the PSR-4 standard.
     *
     * @param string $path The absolute file path.
     *
     * @return string|null The resolved class name, or null if it cannot be resolved.
     */
    private function resolveClassName( string $path ): ?string {
        $relativePath = str_replace( $this->appDir, '', $path );
        $relativePath = ltrim( $relativePath, DIRECTORY_SEPARATOR );
        $classPath    = str_replace( [ '/', '.php' ], [ '\\', '' ], $relativePath );

        return rtrim( $this->namespacePrefix, '\\' ) . '\\' . $classPath;
    }

}